services:
  nginx:
    build: ./nginx
    container_name: "nginx_cont"
    ports:
      - "80:80" # Expose Nginx on port 80
    restart: always
    depends_on:
      - djangoapp
    networks:
      - notes-app-nw

  djangoapp: #when using django, avoid using underscore (_) in service names
    build:
      context: .
    container_name: "django_cont"
    expose:
      - "8000"
    env_file:
      - .env
    restart: always
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://127.0.0.1:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - notes-app-nw

  db:
    image: mysql
    container_name: "db_cont"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=notes
      - MYSQL_PASSWORD=notes_password
    expose:
      - "3306"
    volumes:
      - mysql_data_noteapp:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - notes-app-nw

networks:
  notes-app-nw:

volumes:
  mysql_data_noteapp:
